In [1]:
import numpy as np

# Definição da matriz A
A = np.array([[3.5, 0.2, 1.7],
              [-1.1, 2.3, 1.9],
              [5.0, 1.4, 3.1]])

print("Matriz A:")
print(A)


Matriz A:
[[ 3.5  0.2  1.7]
 [-1.1  2.3  1.9]
 [ 5.   1.4  3.1]]


In [2]:
# Obter a forma escalonada por eliminação gaussiana
def escalonar_matriz(A):
    A_escalonada = A.astype(float)  # Garantir que estamos lidando com valores float
    linhas, colunas = A_escalonada.shape

    for i in range(min(linhas, colunas)):
        # Pivotamento: se o elemento da diagonal for zero, trocar com outra linha
        if A_escalonada[i, i] == 0:
            for k in range(i + 1, linhas):
                if A_escalonada[k, i] != 0:
                    A_escalonada[[i, k]] = A_escalonada[[k, i]]  # Troca as linhas
                    break

        # Zerando os elementos abaixo do pivô
        for j in range(i + 1, linhas):
            fator = A_escalonada[j, i] / A_escalonada[i, i]
            A_escalonada[j] -= fator * A_escalonada[i]

    return A_escalonada

A_escalonada = escalonar_matriz(A)

print("\nForma escalonada de A:")
print(A_escalonada)



Forma escalonada de A:
[[ 3.5         0.2         1.7       ]
 [ 0.          2.36285714  2.43428571]
 [ 0.          0.         -0.47654172]]


In [3]:
# Cálculo do determinante
det_A = np.linalg.det(A)

print("\nDeterminante de A:", det_A)



Determinante de A: -3.9409999999999936


In [4]:
# Verificar se a matriz é singular
if np.isclose(det_A, 0):
    print("\nA matriz A é singular.")
    alternativa_e = True
else:
    alternativa_e = False

# Verificar se a segunda linha é combinação linear da 1ª e 3ª
# Se uma linha for combinação linear das outras, o determinante será zero
# Como já verificamos o determinante, podemos concluir que essa afirmação é verdadeira se det(A) == 0
alternativa_d = alternativa_e

# Comparação das formas escalonadas com as alternativas
alternativa_a = np.allclose(A_escalonada, np.array([[3.5, 0.2, 1.7],
                                                    [0.0, 2.3629, 2.4343],
                                                    [0.0, 0.0, -0.4765]]))

alternativa_c = np.allclose(A_escalonada, np.array([[3.5, 0.2, 1.7],
                                                    [0.0, 2.3629, 2.4343],
                                                    [0.0, 0.0, -0.4567]]))

print("\nAlternativa A está correta?", alternativa_a)
print("Alternativa C está correta?", alternativa_c)
print("Alternativa D está correta?", alternativa_d)
print("Alternativa E está correta?", alternativa_e)



Alternativa A está correta? False
Alternativa C está correta? False
Alternativa D está correta? False
Alternativa E está correta? False


In [6]:
import numpy as np

# Definindo a matriz A
A = np.array([
    [3.5, 0.2, 1.7],
    [-1.1, 2.3, 1.9],
    [5.0, 1.4, 3.1]
], dtype=float)

print("Matriz A:")
print(A)

def escalonar_matriz(matriz):
    m = matriz.copy()
    linhas, colunas = m.shape

    for i in range(min(linhas, colunas)):
        max_linha = i + np.argmax(np.abs(m[i:, i]))
        if i != max_linha:
            m[[i, max_linha]] = m[[max_linha, i]]

        for j in range(i + 1, linhas):
            fator = m[j, i] / m[i, i]
            m[j, i:] -= fator * m[i, i:]

    return m

# Calcula a forma escalonada
A_escalonada = escalonar_matriz(A)
print("\nForma escalonada de A:")
print(A_escalonada)

# Calculando o determinante
det_A = np.linalg.det(A)
print("\nDeterminante de A:", det_A)

# Verificando se a matriz é singular
singular = np.isclose(det_A, 0)
print("\nA matriz A é singular?", singular)

# Verificando combinação linear
L1, L2, L3 = A[0], A[1], A[2]
coeficientes = np.array([L1[:2], L3[:2]]).T
constantes = L2[:2]

try:
    a, b = np.linalg.solve(coeficientes, constantes)
    combinacao_linear = np.isclose(L2[2], a*L1[2] + b*L3[2])
    print("\nA 2a linha é combinação linear da 1a e 3a?", combinacao_linear)
except np.linalg.LinAlgError:
    combinacao_linear = False
    print("\nA 2a linha NÃO é combinação linear da 1a e 3a")

# Comparando com as opções
print("\nAnálise das opções:")

escalonada_opcao_a = np.array([
    [3.5, 0.2, 1.7],
    [0.0, 2.3629, 2.4343],
    [0.0, 0.0, -0.4765]
])

opcao_a = np.allclose(A_escalonada, escalonada_opcao_a, atol=1e-4)
print("a) A forma escalonada é igual à fornecida?", opcao_a)

opcao_b = np.isclose(det_A, 0)
print("b) det(A) = 0?", opcao_b)

escalonada_opcao_c = np.array([
    [3.5, 0.2, 1.7],
    [0.0, 2.3629, 2.4343],
    [0.0, 0.0, -0.4567]
])

opcao_c = np.allclose(A_escalonada, escalonada_opcao_c, atol=1e-4)
print("c) A forma escalonada é igual à fornecida?", opcao_c)

print("d) A 2a linha é combinação linear da 1a e 3a?", combinacao_linear)
print("e) A matriz A é singular?", singular)

Matriz A:
[[ 3.5  0.2  1.7]
 [-1.1  2.3  1.9]
 [ 5.   1.4  3.1]]

Forma escalonada de A:
[[ 5.00000000e+00  1.40000000e+00  3.10000000e+00]
 [ 0.00000000e+00  2.60800000e+00  2.58200000e+00]
 [ 0.00000000e+00 -1.11022302e-16  3.02223926e-01]]

Determinante de A: -3.9409999999999936

A matriz A é singular? False

A 2a linha é combinação linear da 1a e 3a? False

Análise das opções:
a) A forma escalonada é igual à fornecida? False
b) det(A) = 0? False
c) A forma escalonada é igual à fornecida? False
d) A 2a linha é combinação linear da 1a e 3a? False
e) A matriz A é singular? False


In [7]:
# Questao 2

In [11]:
import numpy as np

# Definição da matriz M
M = np.array([[4.230, 5.110, 7.430],
              [-6.555, 1.895, 10.855],
              [10.010, 5.550, 2.670]])

print("Matriz M:")
print(M)


Matriz M:
[[ 4.23   5.11   7.43 ]
 [-6.555  1.895 10.855]
 [10.01   5.55   2.67 ]]


In [12]:
# Cálculo teórico de L2 como combinação linear de L1 e L3
L1 = M[0]
L3 = M[2]
L2_teorico = 2 * L1 - (3/2) * L3

# Comparação com L2 real
L2_real = M[1]

# Verificar se L2_real é aproximadamente igual a L2_teorico
if np.allclose(L2_real, L2_teorico, atol=1e-3):
    print("\nA linha L2 é uma combinação linear de L1 e L3.")
    combinacao_linear = True
else:
    print("\nA linha L2 NÃO é uma combinação linear de L1 e L3.")
    combinacao_linear = False



A linha L2 é uma combinação linear de L1 e L3.


In [13]:
# Cálculo do determinante da matriz M
det_M = np.linalg.det(M)

print("\nDeterminante de M:", det_M)

# Verificação se a matriz é invertível
if np.isclose(det_M, 0, atol=1e-6):
    print("A matriz M NÃO é invertível.")
    inversivel = False
else:
    print("A matriz M é invertível.")
    inversivel = True



Determinante de M: 0.0
A matriz M NÃO é invertível.


In [14]:
# Verificando a alternativa correta
if inversivel and combinacao_linear:
    print("\nAlternativa correta: A (M é invertível e L2 é combinação linear).")
elif not inversivel and not combinacao_linear:
    print("\nAlternativa correta: B (M não é invertível e L2 não é combinação linear).")
elif not inversivel and combinacao_linear:
    print("\nAlternativa correta: E (M não é invertível e L2 é combinação linear).")
elif inversivel and not combinacao_linear:
    print("\nAlternativa correta: C (M é invertível e L2 não é combinação linear).")



Alternativa correta: E (M não é invertível e L2 é combinação linear).


In [15]:
# Questão 3

In [16]:
# Definir a matriz A
A = np.array([
    [ 1,  2,  3],
    [-1,  0,  1],
    [ 0,  2, -1]
])

# Definir o vetor v
# (A questão usa parênteses, mas vamos tratá-lo como um vetor coluna ou linha para cálculo)
# NumPy o tratará corretamente na multiplicação matriz-vetor se for um array 1D.
v = np.array([-1, 0, 3])

print("Matriz A:")
print(A)
print("\nVetor v:")
print(v)

Matriz A:
[[ 1  2  3]
 [-1  0  1]
 [ 0  2 -1]]

Vetor v:
[-1  0  3]


In [17]:
# Calcular a raiz quadrada de 2
sqrt_2 = np.sqrt(2)
print(f"\nRaiz quadrada de 2: {sqrt_2:.8f}") # Mostra com 8 casas decimais

# Calcular o vetor v escalado: sqrt(2) * v
v_scaled = sqrt_2 * v
print("\nVetor v escalado (sqrt(2) * v):")
print(v_scaled)

# Calcular o vetor u = A * v_scaled
# Usamos o operador @ para multiplicação de matrizes/vetores no NumPy
u = A @ v_scaled
# Alternativamente: u = np.dot(A, v_scaled)

print("\nVetor u = A @ v_scaled:")
print(u)
# Para comparar com as opções, podemos imprimir com mais casas decimais
print(f"Vetor u (com mais precisão): [{u[0]:.8f} {u[1]:.8f} {u[2]:.8f}]")


Raiz quadrada de 2: 1.41421356

Vetor v escalado (sqrt(2) * v):
[-1.41421356  0.          4.24264069]

Vetor u = A @ v_scaled:
[11.3137085   5.65685425 -4.24264069]
Vetor u (com mais precisão): [11.31370850 5.65685425 -4.24264069]


In [18]:
# Calcular a norma (magnitude) do vetor u
norm_u = np.linalg.norm(u)
print(f"\nNorma do vetor u ||u||: {norm_u:.8f}")

# Calcular o vetor unitário û = u / ||u||
# Verifica se a norma não é zero para evitar divisão por zero
if norm_u == 0:
    print("Erro: A norma do vetor u é zero. Não é possível calcular o vetor unitário.")
    u_hat = np.zeros_like(u) # Ou outra forma de lidar com o vetor nulo
else:
    u_hat = u / norm_u

print("\nVetor unitário û = u / ||u||:")
print(u_hat)
# Para comparar com as opções, podemos imprimir com mais casas decimais
print(f"Vetor û (com mais precisão): [{u_hat[0]:.8f} {u_hat[1]:.8f} {u_hat[2]:.8f}]")

# Podemos verificar se a norma do vetor unitário é 1 (como esperado)
norm_u_hat = np.linalg.norm(u_hat)
print(f"\nNorma do vetor unitário ||û||: {norm_u_hat:.1f}") # Deve ser 1.0


Norma do vetor u ||u||: 13.34166406

Vetor unitário û = u / ||u||:
[ 0.8479983   0.42399915 -0.31799936]
Vetor û (com mais precisão): [0.84799830 0.42399915 -0.31799936]

Norma do vetor unitário ||û||: 1.0


In [19]:
print("\n--- Comparação Final ---")
print(f"Vetor u calculado: [{u[0]:.8f} {u[1]:.8f} {u[2]:.8f}]")
print(f"Vetor û calculado: [{u_hat[0]:.8f} {u_hat[1]:.8f} {u_hat[2]:.8f}]")

print("\nA opção que apresenta os vetores u e û nesta ordem e com valores correspondentes é a (d).")
print("Opção (d):")
print("u ≈ [ 11.3137085  5.65685425 -4.24264069 ]")
print("û ≈ [  0.8479983  0.42399915 -0.31799936 ]")


--- Comparação Final ---
Vetor u calculado: [11.31370850 5.65685425 -4.24264069]
Vetor û calculado: [0.84799830 0.42399915 -0.31799936]

A opção que apresenta os vetores u e û nesta ordem e com valores correspondentes é a (d).
Opção (d):
u ≈ [ 11.3137085  5.65685425 -4.24264069 ]
û ≈ [  0.8479983  0.42399915 -0.31799936 ]
